---
name: Bug Report
description: File a bug report
title: '[Bug: ]'
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      options:
        - label: I use the newest version of bruno.
          required: true
  - type: checkboxes
    attributes:
      options:
        - label: I've searched existing issues and found nothing related to my issue.
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug.
    validiations:
      required: true
  - type: textarea
    attributes:
      label: .bru file to reproduce the bug
      descripiton: Attach your .bru file here that can reqroduce the problem.
    validiation:
      required: false
  - type: textarea
    attributes:
      label: Screenshots/Live demo link
      description: Add some screenshots to help explain the problem.
    validiations:
      required: true
