import { faker } from '@faker-js/faker';

export function getMockData(placeholder: string) {
  switch (placeholder) {
    case '$guid':
      return faker.string.uuid();
    case '$timestamp':
      return faker.date.anytime().getTime().toString();
    case '$isoTimestamp':
      return faker.date.anytime().toISOString();
    case '$randomUUID':
      return faker.string.uuid();
    case '$randomAlphaNumeric':
      return faker.string.alphanumeric();
    case '$randomBoolean':
      return faker.datatype.boolean();
    case '$randomInt':
      return faker.number.int();
    case '$randomColor':
      return faker.color.human();
    case '$randomHexColor':
      return faker.color.rgb();
    case '$randomAbbreviation':
      return faker.hacker.abbreviation();
    case '$randomIP':
      return faker.internet.ip();
    case '$randomIPV4':
      return faker.internet.ipv4();
    case '$randomIPV6':
      return faker.internet.ipv6();
    case '$randomMACAddress':
      return faker.internet.mac();
    case '$randomPassword':
      return faker.internet.password();
    case '$randomLocale':
      return faker.location.countryCode();
    case '$randomUserAgent':
      return faker.internet.userAgent();
    case '$randomProtocol':
      return faker.internet.protocol();
    case '$randomSemver':
      return faker.system.semver();
    case '$randomFirstName':
      return faker.person.firstName();
    case '$randomLastName':
      return faker.person.lastName();
    case '$randomFullName':
      return faker.person.fullName();
    case '$randomNamePrefix':
      return faker.person.prefix();
    case '$randomNameSuffix':
      return faker.person.suffix();
    case '$randomJobArea':
      return faker.person.jobArea();
    case '$randomJobDescriptor':
      return faker.person.jobDescriptor();
    case '$randomJobTitle':
      return faker.person.jobTitle();
    case '$randomJobType':
      return faker.person.jobType();
    case '$randomPhoneNumber':
      return faker.phone.number();
    case '$randomPhoneNumberExt':
      return faker.phone.number();
    case '$randomCity':
      return faker.location.city();
    case '$randomStreetName':
      return faker.location.street();
    case '$randomStreetAddress':
      return faker.location.streetAddress();
    case '$randomCountry':
      return faker.location.country();
    case '$randomCountryCode':
      return faker.location.countryCode();
    case '$randomLatitude':
      return faker.location.latitude();
    case '$randomLongitude':
      return faker.location.longitude();
    case '$randomAvatarImage':
      return faker.image.avatar();
    case '$randomImageUrl':
      return faker.image.url();
    case '$randomAbstractImage':
      return faker.image.urlLoremFlickr({ category: 'abstract' });
    case '$randomAnimalsImage':
      return faker.image.urlLoremFlickr({ category: 'animals' });
    case '$randomBusinessImage':
      return faker.image.urlLoremFlickr({ category: 'business' });
    case '$randomCatsImage':
      return faker.image.urlLoremFlickr({ category: 'cats' });
    case '$randomCityImage':
      return faker.image.urlLoremFlickr({ category: 'city' });
    case '$randomFoodImage':
      return faker.image.urlLoremFlickr({ category: 'food' });
    case '$randomNightlifeImage':
      return faker.image.urlLoremFlickr({ category: 'nightlife' });
    case '$randomFashionImage':
      return faker.image.urlLoremFlickr({ category: 'fashion' });
    case '$randomPeopleImage':
      return faker.image.urlLoremFlickr({ category: 'people' });
    case '$randomNatureImage':
      return faker.image.urlLoremFlickr({ category: 'nature' });
    case '$randomSportsImage':
      return faker.image.urlLoremFlickr({ category: 'sports' });
    case '$randomTransportImage':
      return faker.image.urlLoremFlickr({ category: 'transport' });
    case '$randomImageDataUri':
      return faker.image.dataUri();
    case '$randomBankAccount':
      return faker.finance.accountNumber();
    case '$randomBankAccountName':
      return faker.finance.accountName();
    case '$randomCreditCardMask':
      return faker.finance.iban().replace(/(?<=.{4})\w(?=.{2})/g, '*');
    case '$randomBankAccountBic':
      return faker.finance.bic();
    case '$randomBankAccountIban':
      return faker.finance.iban();
    case '$randomTransactionType':
      return faker.finance.transactionType();
    case '$randomCurrencyCode':
      return faker.finance.currencyCode();
    case '$randomCurrencyName':
      return faker.finance.currencyName();
    case '$randomCurrencySymbol':
      return faker.finance.currencySymbol();
    case '$randomBitcoin':
      return faker.finance.bitcoinAddress();
    case '$randomCompanyName':
      return faker.company.name();
    case '$randomCompanySuffix':
      return faker.company.name();
    case '$randomBs':
      return faker.company.buzzPhrase();
    case '$randomBsAdjective':
      return faker.company.buzzAdjective();
    case '$randomBsBuzz':
      return faker.company.buzzVerb();
    case '$randomBsNoun':
      return faker.company.buzzNoun();
    case '$randomCatchPhrase':
      return faker.company.catchPhrase();
    case '$randomCatchPhraseAdjective':
      return faker.company.catchPhraseAdjective();
    case '$randomCatchPhraseDescriptor':
      return faker.company.catchPhraseDescriptor();
    case '$randomCatchPhraseNoun':
      return faker.company.catchPhraseNoun();
    case '$randomDatabaseColumn':
      return faker.database.column();
    case '$randomDatabaseType':
      return faker.database.type();
    case '$randomDatabaseCollation':
      return faker.database.collation();
    case '$randomDatabaseEngine':
      return faker.database.engine();
    case '$randomDateFuture':
      return faker.date.future().toISOString();
    case '$randomDatePast':
      return faker.date.past().toISOString();
    case '$randomDateRecent':
      return faker.date.recent().toISOString();
    case '$randomWeekday':
      return faker.date.weekday();
    case '$randomMonth':
      return faker.date.month();
    case '$randomDomainName':
      return faker.internet.domainName();
    case '$randomDomainSuffix':
      return faker.internet.domainSuffix();
    case '$randomDomainWord':
      return faker.internet.domainWord();
    case '$randomEmail':
      return faker.internet.email();
    case '$randomExampleEmail':
      return faker.internet.exampleEmail();
    case '$randomUserName':
      return faker.internet.username();
    case '$randomUrl':
      return faker.internet.url();
    case '$randomFileName':
      return faker.system.fileName();
    case '$randomFileType':
      return faker.system.fileType();
    case '$randomFileExt':
      return faker.system.fileExt();
    case '$randomCommonFileName':
      return faker.system.commonFileName();
    case '$randomCommonFileType':
      return faker.system.commonFileType();
    case '$randomCommonFileExt':
      return faker.system.commonFileExt();
    case '$randomFilePath':
      return faker.system.filePath();
    case '$randomDirectoryPath':
      return faker.system.directoryPath();
    case '$randomMimeType':
      return faker.system.mimeType();
    case '$randomPrice':
      return faker.commerce.price();
    case '$randomProduct':
      return faker.commerce.product();
    case '$randomProductAdjective':
      return faker.commerce.productAdjective();
    case '$randomProductMaterial':
      return faker.commerce.productMaterial();
    case '$randomProductName':
      return faker.commerce.productName();
    case '$randomDepartment':
      return faker.commerce.department();
    case '$randomNoun':
      return faker.hacker.noun();
    case '$randomVerb':
      return faker.hacker.verb();
    case '$randomIngverb':
      return faker.hacker.ingverb();
    case '$randomAdjective':
      return faker.hacker.adjective();
    case '$randomWord':
      return faker.hacker.noun();
    case '$randomWords':
      return faker.lorem.words();
    case '$randomPhrase':
      return faker.hacker.phrase();
    case '$randomLoremWord':
      return faker.lorem.word();
    case '$randomLoremWords':
      return faker.lorem.words();
    case '$randomLoremSentence':
      return faker.lorem.sentence();
    case '$randomLoremSentences':
      return faker.lorem.sentences();
    case '$randomLoremParagraph':
      return faker.lorem.paragraph();
    case '$randomLoremParagraphs':
      return faker.lorem.paragraphs();
    case '$randomLoremText':
      return faker.lorem.text();
    case '$randomLoremSlug':
      return faker.lorem.slug();
    case '$randomLoremLines':
      return faker.lorem.lines();
    default:
      return null;
  }
}
