export const mockVariables = {
  $guid: 'Dynamically generated, e.g. 5d27c6e4-b8c4-446b-921c-d1b6b10f3b5f',
  $timestamp: 'Dynamically generated, e.g. 1633072800000',
  $isoTimestamp: 'Dynamically generated, e.g. 2023-10-05T14:48:00.000Z',
  $randomUUID: 'Dynamically generated, e.g. 1b2a3c4d-5f6a-7b8c-9d0e-1f2a3b4c5d6e',
  $randomAlphaNumeric: 'Dynamically generated, e.g. aB3xYz12',
  $randomBoolean: 'Dynamically generated, e.g. true',
  $randomInt: 'Dynamically generated, e.g. 42',
  $randomColor: 'Dynamically generated, e.g. red',
  $randomHexColor: 'Dynamically generated, e.g. #ff5733',
  $randomAbbreviation: 'Dynamically generated, e.g. API',
  $randomIP: 'Dynamically generated, e.g. 192.168.0.1',
  $randomIPV4: 'Dynamically generated, e.g. 192.168.0.1',
  $randomIPV6: 'Dynamically generated, e.g. 2001:0db8:85a3:0000:0000:8a2e:0370:7334',
  $randomMACAddress: 'Dynamically generated, e.g. 00:1A:2B:3C:4D:5E',
  $randomPassword: 'Dynamically generated, e.g. p@ssw0rd!',
  $randomLocale: 'Dynamically generated, e.g. US',
  $randomUserAgent: 'Dynamically generated, e.g. Mozilla/5.0',
  $randomProtocol: 'Dynamically generated, e.g. https',
  $randomSemver: 'Dynamically generated, e.g. 1.0.0',
  $randomFirstName: 'Dynamically generated, e.g. John',
  $randomLastName: 'Dynamically generated, e.g. Doe',
  $randomFullName: 'Dynamically generated, e.g. John Doe',
  $randomNamePrefix: 'Dynamically generated, e.g. Mr.',
  $randomNameSuffix: 'Dynamically generated, e.g. Jr.',
  $randomJobArea: 'Dynamically generated, e.g. Engineering',
  $randomJobDescriptor: 'Dynamically generated, e.g. Lead',
  $randomJobTitle: 'Dynamically generated, e.g. Software Engineer',
  $randomJobType: 'Dynamically generated, e.g. Full-time',
  $randomPhoneNumber: 'Dynamically generated, e.g. 555-1234',
  $randomPhoneNumberExt: 'Dynamically generated, e.g. 555-1234 x123',
  $randomCity: 'Dynamically generated, e.g. New York',
  $randomStreetName: 'Dynamically generated, e.g. Maple Street',
  $randomStreetAddress: 'Dynamically generated, e.g. 123 Maple Street',
  $randomCountry: 'Dynamically generated, e.g. United States',
  $randomCountryCode: 'Dynamically generated, e.g. US',
  $randomLatitude: 'Dynamically generated, e.g. 40.7128',
  $randomLongitude: 'Dynamically generated, e.g. -74.0060',
  $randomAvatarImage: 'Dynamically generated, e.g. https://example.com/avatar.jpg',
  $randomImageUrl: 'Dynamically generated, e.g. https://example.com/image.jpg',
  $randomAbstractImage: 'Dynamically generated, e.g. https://example.com/abstract.jpg',
  $randomAnimalsImage: 'Dynamically generated, e.g. https://example.com/animals.jpg',
  $randomBusinessImage: 'Dynamically generated, e.g. https://example.com/business.jpg',
  $randomCatsImage: 'Dynamically generated, e.g. https://example.com/cats.jpg',
  $randomCityImage: 'Dynamically generated, e.g. https://example.com/city.jpg',
  $randomFoodImage: 'Dynamically generated, e.g. https://example.com/food.jpg',
  $randomNightlifeImage: 'Dynamically generated, e.g. https://example.com/nightlife.jpg',
  $randomFashionImage: 'Dynamically generated, e.g. https://example.com/fashion.jpg',
  $randomPeopleImage: 'Dynamically generated, e.g. https://example.com/people.jpg',
  $randomNatureImage: 'Dynamically generated, e.g. https://example.com/nature.jpg',
  $randomSportsImage: 'Dynamically generated, e.g. https://example.com/sports.jpg',
  $randomTransportImage: 'Dynamically generated, e.g. https://example.com/transport.jpg',
  $randomImageDataUri: 'Dynamically generated, e.g. data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA...',
  $randomBankAccount: 'Dynamically generated, e.g. 123456789',
  $randomBankAccountName: 'Dynamically generated, e.g. John Doe',
  $randomCreditCardMask: 'Dynamically generated, e.g. 1234********5678',
  $randomBankAccountBic: 'Dynamically generated, e.g. BANKUS33',
  $randomBankAccountIban: 'Dynamically generated, e.g. DE89 3704 0044 0532 0130 00',
  $randomTransactionType: 'Dynamically generated, e.g. deposit',
  $randomCurrencyCode: 'Dynamically generated, e.g. USD',
  $randomCurrencyName: 'Dynamically generated, e.g. US Dollar',
  $randomCurrencySymbol: 'Dynamically generated, e.g. $',
  $randomBitcoin: 'Dynamically generated, e.g. 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
  $randomCompanyName: 'Dynamically generated, e.g. TechCorp',
  $randomCompanySuffix: 'Dynamically generated, e.g. Inc',
  $randomBs: 'Dynamically generated, e.g. innovative solutions',
  $randomBsAdjective: 'Dynamically generated, e.g. innovative',
  $randomBsBuzz: 'Dynamically generated, e.g. leverage',
  $randomBsNoun: 'Dynamically generated, e.g. paradigm',
  $randomCatchPhrase: 'Dynamically generated, e.g. Innovative solutions for tomorrow',
  $randomCatchPhraseAdjective: 'Dynamically generated, e.g. innovative',
  $randomCatchPhraseDescriptor: 'Dynamically generated, e.g. cutting-edge',
  $randomCatchPhraseNoun: 'Dynamically generated, e.g. solutions',
  $randomDatabaseColumn: 'Dynamically generated, e.g. id',
  $randomDatabaseType: 'Dynamically generated, e.g. int',
  $randomDatabaseCollation: 'Dynamically generated, e.g. utf8_general_ci',
  $randomDatabaseEngine: 'Dynamically generated, e.g. InnoDB',
  $randomDateFuture: 'Dynamically generated, e.g. 2024-12-31T23:59:59.999Z',
  $randomDatePast: 'Dynamically generated, e.g. 2022-01-01T00:00:00.000Z',
  $randomDateRecent: 'Dynamically generated, e.g. 2023-10-01T00:00:00.000Z',
  $randomWeekday: 'Dynamically generated, e.g. Monday',
  $randomMonth: 'Dynamically generated, e.g. October',
  $randomDomainName: 'Dynamically generated, e.g. example.com',
  $randomDomainSuffix: 'Dynamically generated, e.g. com',
  $randomDomainWord: 'Dynamically generated, e.g. example',
  $randomEmail: 'Dynamically generated, e.g. john.doe@example.com',
  $randomExampleEmail: 'Dynamically generated, e.g. example@example.com',
  $randomUserName: 'Dynamically generated, e.g. johndoe',
  $randomUrl: 'Dynamically generated, e.g. https://example.com',
  $randomFileName: 'Dynamically generated, e.g. document.txt',
  $randomFileType: 'Dynamically generated, e.g. text',
  $randomFileExt: 'Dynamically generated, e.g. txt',
  $randomCommonFileName: 'Dynamically generated, e.g. document.txt',
  $randomCommonFileType: 'Dynamically generated, e.g. text',
  $randomCommonFileExt: 'Dynamically generated, e.g. txt',
  $randomFilePath: 'Dynamically generated, e.g. /path/to/file.txt',
  $randomDirectoryPath: 'Dynamically generated, e.g. /path/to/directory',
  $randomMimeType: 'Dynamically generated, e.g. text/plain',
  $randomPrice: 'Dynamically generated, e.g. $19.99',
  $randomProduct: 'Dynamically generated, e.g. Widget',
  $randomProductAdjective: 'Dynamically generated, e.g. Amazing',
  $randomProductMaterial: 'Dynamically generated, e.g. Plastic',
  $randomProductName: 'Dynamically generated, e.g. Amazing Widget',
  $randomDepartment: 'Dynamically generated, e.g. Electronics',
  $randomNoun: 'Dynamically generated, e.g. Widget',
  $randomVerb: 'Dynamically generated, e.g. Run',
  $randomIngverb: 'Dynamically generated, e.g. Running',
  $randomAdjective: 'Dynamically generated, e.g. Amazing',
  $randomWord: 'Dynamically generated, e.g. Widget',
  $randomWords: 'Dynamically generated, e.g. Amazing Widget',
  $randomPhrase: 'Dynamically generated, e.g. Amazing Widgets',
  $randomLoremWord: 'Dynamically generated, e.g. lorem',
  $randomLoremWords: 'Dynamically generated, e.g. lorem ipsum',
  $randomLoremSentence: 'Dynamically generated, e.g. Lorem ipsum dolor sit amet.',
  $randomLoremSentences: 'Dynamically generated, e.g. Lorem ipsum dolor sit amet. Consectetur adipiscing elit.',
  $randomLoremParagraph: 'Dynamically generated, e.g. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  $randomLoremParagraphs:
    'Dynamically generated, e.g. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  $randomLoremText: 'Dynamically generated, e.g. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  $randomLoremSlug: 'Dynamically generated, e.g. lorem-ipsum',
  $randomLoremLines: 'Dynamically generated, e.g. Lorem ipsum\ndolor sit amet'
};
